<?php
namespace App\Http\Controllers;
use App\Models\{AdminUser,AdminActivityLog,Faculty}; use Illuminate\Http\Request; use Illuminate\Support\Facades\Hash; use Symfony\Component\HttpFoundation\StreamedResponse;
class AdminController extends Controller {
 public function login(){return view('admin.index');}
 public function authenticate(Request $r){$d=$r->validate(['username'=>'required','password'=>'required']);$a=AdminUser::where('username',$d['username'])->where('is_active',true)->first();if(!$a||!Hash::check($d['password'],$a->password))return response()->json(['message'=>'Invalid User ID or Password.'],422);$r->session()->regenerate();$r->session()->put('admin_id',$a->id);$this->log($a,'login');return $a->only(['id','username','role']);}
 public function logout(Request $r){$r->session()->invalidate();$r->session()->regenerateToken();return ['ok'=>true];}
 public function dashboard(){return ['active'=>Faculty::where('is_deleted',false)->orderBy('name')->get(),'deleted'=>Faculty::where('is_deleted',true)->orderBy('name')->get(),'admins'=>AdminUser::select('id','username','role','is_active','created_at')->get(),'activity'=>AdminActivityLog::latest()->limit(100)->get()];}
 public function updateFaculty(Request $r,Faculty $faculty){$d=$r->validate(['email'=>'required|email','name'=>'nullable|string','department'=>'nullable|string','research_groups'=>'nullable|string','keywords'=>'nullable|string','showcase_interest'=>'nullable|string','ai_research'=>'nullable|string','enterprise_projects'=>'nullable|string','future_directions'=>'nullable|string','external_organisations'=>'nullable|string','support_training'=>'nullable|string','additional_comments'=>'nullable|string','consent'=>'nullable|string']);$d['last_modified_time']=now();$faculty->update($d);$this->log($this->me(),'edit',$faculty->id,$faculty->email);return $faculty->fresh();}
 public function softDelete(Faculty $faculty){$faculty->update(['is_deleted'=>true,'deleted_at'=>now(),'last_modified_time'=>now()]);$this->log($this->me(),'soft_delete',$faculty->id,$faculty->email);return ['ok'=>true];}
 public function restore(Faculty $faculty){$faculty->update(['is_deleted'=>false,'deleted_at'=>null,'last_modified_time'=>now()]);$this->log($this->me(),'restore',$faculty->id,$faculty->email);return ['ok'=>true];}
 public function admins(){return AdminUser::select('id','username','role','is_active','created_at')->orderBy('username')->get();}
 public function createAdmin(Request $r){$d=$r->validate(['username'=>'required|unique:admin_login_users,username','password'=>'required|min:8','role'=>'required|in:admin,super_admin']);$a=AdminUser::create(['username'=>$d['username'],'password'=>Hash::make($d['password']),'role'=>$d['role'],'is_active'=>true]);$this->log($this->me(),'create_admin',$a->id,$a->username);return $a->only(['id','username','role','is_active','created_at']);}
 public function setAdminActive(Request $r,AdminUser $adminUser){if($adminUser->id==$this->me()->id)return response()->json(['message'=>'You cannot disable yourself.'],422);$d=$r->validate(['is_active'=>'required|boolean']);$adminUser->update($d);$this->log($this->me(),$d['is_active']?'reactivate_admin':'disable_admin',$adminUser->id,$adminUser->username);return ['ok'=>true];}
 public function activity(){return AdminActivityLog::latest()->limit(200)->get();}
 public function export(){return new StreamedResponse(function(){ $out=fopen('php://output','w');fputcsv($out,['Name','Email','Department','Research Groups','Keywords','Showcase Interest','AI Research','Enterprise / KE','Future Directions','External Organisations','Support / Training','Additional Comments','Consent','Deleted','Deleted At','Last Modified']);foreach(Faculty::orderBy('name')->get() as $r)fputcsv($out,[$r->name,$r->email,$r->department,$r->research_groups,$r->keywords,$r->showcase_interest,$r->ai_research,$r->enterprise_projects,$r->future_directions,$r->external_organisations,$r->support_training,$r->additional_comments,$r->consent,$r->is_deleted?'Yes':'No',$r->deleted_at,$r->last_modified_time]);fclose($out);},200,['Content-Type'=>'text/csv','Content-Disposition'=>'attachment; filename="faculty-data.csv"']);}
 private function me(){return AdminUser::find(session('admin_id'));} private function log($a,$action,$id=null,$details=null){if($a)AdminActivityLog::create(['admin_username'=>$a->username,'action'=>$action,'record_id'=>$id,'details'=>$details]);}
}
